on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USER}}
          password: ${{secrets.FTP_PASS}}
          protocol: ftps
          port: ${{secrets.FTP_PORT}}

      - name: Copy ENV Laravel Configuration for CI
        run: |
          php -r "file_exists('source/.env') || copy('source/.env.github-actions', 'source/.env');"
      - name: Install Composer & NPM Dependencies
        run: |
          composer install -d source -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
          npm install
          npm run prod
          {{@if {{$__variables__/LARAVEL_ENV_APP_KEY}} == ''}}
      - name: Generate Laravel Application Key
        run: |
          php artisan key:generate
          {{@endif}}
